services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    environment:
      - QDRANT__SERVICE__HOST=0.0.0.0
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks:
      - nornikel-net

  nlu:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: nlu
    restart: always
    volumes:
      - ${LOCAL_HUGGINGFACE_MODELS}:/opt/.cache/huggingface
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - HF_HOME=/opt/.cache/huggingface
    env_file:
      - .env
    depends_on:
      - qdrant
    networks:
      - nornikel-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

configs:
  qdrant_config:
    content: |
      log_level: INFO

networks:
  nornikel-net:
    driver: bridge
